{{- if and .Values.nodeAgent.directAlerts.enabled .Values.nodeAgent.directAlerts.keygen.enabled }}
{{- $consumerNs := default .Values.ksNamespace .Values.nodeAgent.directAlerts.consumerNamespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-agent-direct-keygen
  namespace: {{ .Values.ksNamespace }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name "tier" .Values.global.namespaceTier) | nindent 4 }}
{{- end }}
