{{- if .Values.nodeAgent.bundleSigning.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-agent-bundle-policy
  namespace: {{ .Values.ksNamespace }}
  labels:
    kubescape.io/ignore: "true"
data:
  trust-policy.json: |
{{ .Values.nodeAgent.bundleSigning.trustPolicy | indent 4 }}
{{- if .Values.nodeAgent.bundleSigning.rootPublicKey }}
  root.pub: |
{{ .Values.nodeAgent.bundleSigning.rootPublicKey | indent 4 }}
{{- end }}
{{- end }}
